
import type {PmDoc} from 'pm-to-typst'


// Top-level request for generating a Typst document / PDF
export interface TypstRequest {
    title:string
    page:PageConfig
    typography:TypographyConfig
    features:FeatureConfig
    content:TypstContentItem[]
    arrangement:'normal'|'book'|'booklet'
    show_pages:boolean
    booklet_portrait:boolean
}


// Document-wide display options for the chapter (#ch), verse (#vn) and words-of-Jesus (#wj)
// markers. These drive global function definitions in the preamble rather than per-passage.
export interface FeatureConfig {
    show_chapters:boolean
    show_chapters_style:'divider'|'float'|'heading'
    show_verses:boolean
    show_wj:boolean
    show_wj_color:string|null
    show_wj_bold:boolean
    show_wj_italic:boolean
}


// Page dimensions and margins
export interface PageConfig {
    // Typst-native unit strings, e.g. "210mm", "8.5in"
    width:string
    height:string
    margin_top:string
    margin_bottom:string
    margin_left:string
    margin_right:string
}


// Font and paragraph settings
export interface TypographyConfig {
    font_family:string
    font_fallbacks:string[]
    font_size:string        // e.g. "10pt"
    line_height:number      // e.g. 1.75 — module converts to Typst leading
    justify:boolean|null    // null = auto (justify when width permits)
    text_color:string|null  // Hex color for all text; unset = no fill rule (Typst default)
}


// Union of all content item types
export type TypstContentItem = TypstPassage | TypstTitlePage | TypstCustomPage | TypstLinesPage


// Bible passage with all display configuration
export interface TypstPassage {
    type:'passage'
    // Pre-rendered Typst content per translation (1 or 2 bibles)
    bibles:BiblePassageData[]
    // How multiple translations are laid out (single bible ignores this)
    multi_layout:'columns'|'alternate'
    // Which side gets blank/lines pages (null = no half-blank)
    half_blank:'left'|'right'|null
    // Per-passage content display toggles (chapter/verse/wj markers are document-wide,
    // see FeatureConfig on TypstRequest)
    show_headings:boolean
    show_footnotes:boolean
    // Dotted lines on blank half-pages
    show_lines:boolean
    // Column layout: 'auto' uses book code to decide, 1 or 2 forces column count
    columns:'auto'|1|2
    column_gap:string       // e.g. "5mm"
    // Book code for auto-column detection (e.g. "psa", "isa")
    book:string
    // Optional passage reference displayed above content
    passage_title:string|null
    // Ensure this starts on its own sheet with blank rear
    alone:boolean
    // Begin on a fresh page (false = merge onto the same page as the section above)
    new_page:boolean
}


// Pre-rendered Typst markup for one translation's passage
export interface BiblePassageData {
    content:string
}


// Decorative title page
export interface TypstTitlePage {
    type:'title'
    title:string
    subtitle:string
    icon:string|null            // Resolved + recolored icon SVG (from an Iconify ID or raw SVG)
    icon_size:number            // Size multiplier for the icon (1 = default)
    // One corner SVG string — module mirrors to all 4 corners
    pattern_svg:string|null
    color_primary:string        // Hex color for text
    color_secondary:string      // Hex color for pattern and icon
    // Ensure this starts on its own sheet with blank rear
    alone:boolean
}


// Custom content page (copyright, notes, etc.)
export interface TypstCustomPage {
    type:'custom'
    content:string              // Typst markup generated by the app
    position:'top'|'middle'|'bottom'
    // Begin on a fresh page (false = merge onto the same page as the section above)
    new_page:boolean
}


// Page of dotted lines for notetaking
export interface TypstLinesPage {
    type:'lines'
    spacing:string              // e.g. "10mm"
}


// Function signature for compiling a Typst source string to PDF bytes
export type CompileFn = (source:string) => Promise<Uint8Array>


// --- Blueprint input model ---------------------------------------------------------------
// The user-facing options structure selected in the app. BibleContent.resolve() turns a
// Blueprint into a (fully resolved) TypstRequest, so the same options can drive both the
// in-browser and server (Node) pipelines.


// A complete set of user-selected options for generating a document
export interface Blueprint {

    // Title used in PDF meta and download file name
    title:string

    // Printing
    service_id:string  // printing service id, or 'custom' for manual bleed/spine
    size_id:string  // named size id, or '' for custom dimensions
    page_count:number
    binding_type:string
    ink_type:string
    paper_type:string
    custom_unit:'mm'|'inch'
    custom_trim_width:number
    custom_trim_height:number
    custom_bleed:number
    custom_spine:number
    booklet:boolean
    booklet_portrait:boolean

    // Content
    content:ContentItem[]
    bibles:[string, ...string[]]
    bibles_layout:'alternate'|'columns'

    // Features
    show_headings:boolean
    show_chapters:boolean
    show_chapters_style:'divider'|'float'|'heading'
    show_verses:boolean
    show_pages:boolean
    show_footnotes:boolean
    show_wj:boolean
    show_wj_color:string|null
    show_wj_bold:boolean
    show_wj_italic:boolean
    show_lines:boolean
    notes:string|null
    crossref:'small'|'medium'|'large'|null
    half_blank:'left'|'right'|null

    // Style
    font_family:string
    font_size:number
    line_height:number
    justify:null|boolean
    text_color:string|null
    columns:null|boolean

    // Spacing
    margin_unit:'mm'|'in'
    margin_top:number
    margin_bottom:number
    margin_inner:number
    margin_outer:number
    column_gap:number

    // Legal
    public_domain:boolean
    app_link:boolean
}


// A single item in the document's content list
export type ContentItem = ContentTitle|ContentPassage|ContentCustom


// Decorative title page item
export interface ContentTitle {
    type:'title'
    id:string
    title:string
    subtitle:string
    icon:string|null
    icon_size:number  // Size multiplier for the icon (1 = default)
    pattern:string
    color_primary:string|null
    color_secondary:string|null
    alone:boolean  // Ensure appears on own page with blank rear (and also not on rear of previous)
}


// Bible passage reference item (resolved to fetched content at render time)
export interface ContentPassage {
    type:'passage'
    id:string
    book:string
    start_chapter:number|null
    start_verse:number|null
    end_chapter:number|null
    end_verse:number|null
    title:boolean
    new_page:boolean
}


// Custom rich-text page item (ProseMirror/Tiptap doc, converted to Typst at render time)
export interface ContentCustom {
    type:'custom'
    id:string
    name:string
    doc:PmDoc
    position:'top'|'middle'|'bottom'
    new_page:boolean
}


// --- Study notes -------------------------------------------------------------------------
// Fetched notes data for one book, already pre-rendered as Typst markup by the content API


// A note that spans a verse range, inserted at its start verse
export interface TypstNoteRange {
    start_chapter:number
    start_verse:number
    end_chapter:number
    end_verse:number
    contents:string  // pre-rendered Typst markup
}


// A book's full set of study notes: single-verse notes plus verse-range notes
export interface TypstNotesFile {
    notes_id:string
    book:string
    verses:Record<string, Record<string, string>>  // chapter -> verse -> Typst markup
    ranges:TypstNoteRange[]
}
