
// Generate src/generated/patterns.ts by inlining the title-page pattern SVGs as string
// constants, so they embed into the compiled JS for both the browser and Node builds (no
// bundler-specific `?raw` import needed). Regenerate after changing assets/patterns/ — wired
// into .bin/build_typst.

import {readFileSync, writeFileSync} from 'node:fs'
import {join, dirname} from 'node:path'
import {fileURLToPath} from 'node:url'


const here = dirname(fileURLToPath(import.meta.url))
const assets_dir = join(here, 'assets', 'patterns')
const out_file = join(here, 'src', 'generated', 'patterns.ts')


// Display order shown in the title-page editor (grouped by style)
const ORDER = [
    'simple', 'short', 'subtle',
    'twist', 'vine', 'royal', 'abstract', 'burst',
    'straight', 'detailed', 'formal',
    'path', 'logic',
    'rays',
]


// Read each SVG and emit a string-keyed record literal in display order
const entries = ORDER.map(name => {
    const svg = readFileSync(join(assets_dir, `${name}.svg`), 'utf-8').trim()
    return `    ${JSON.stringify(name)}: ${JSON.stringify(svg)},`
})


// Compose the generated module (auto-generated; values use JSON-style double quotes)
const out = `
// AUTO-GENERATED by typst/gen_patterns.ts — do not edit by hand.
// Title-page decorative pattern SVGs, inlined as strings so they embed into the compiled JS
// for both the browser and Node builds. Regenerate after changing assets/patterns/.


// Pattern name → corner SVG markup (one corner; the renderer mirrors it to all four)
export const PATTERNS:Record<string, string> = {
${entries.join('\n')}
}
`

writeFileSync(out_file, out.trimStart() + '\n')
console.log(`Wrote ${out_file} (${ORDER.length} patterns)`)
